name: end-to-end-challange

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install
        run: npm install

      - name: test
        run: npm test
